### ISSUE TITLE
Table ends up in crashed state

### ISSUE THREAD

**Issue by hippich** [hippich/Bitcoin-Poker-Room#84]
## Summary (full log attached)<br>

<p>
Hand 262007 starts. Player 11110 (theFED) is included as part of the player<br>
list at the start of the hand in position 5 (he had just played in the previous<br>
hand 262006):<br>
</p>

<blockquote>
<p>
2011-07-17 06:59:38+0000 [-] <a class="missing wiki">PokerTable?</a>: Dealing hand Issgar 4/262007<br>
2011-07-17 06:59:38+0000 [-] [Server]<a class="missing wiki">11661?</a> Dealing Hold'em hand number 262007<br>
2011-07-17 06:59:38+0000 [-] [Server]<a class="missing wiki">11661?</a> player list: [9322, 10455, 8904, 11098, 9822, 11110, 11251]<br>
</p>
</blockquote>

<p>
Player 11110 posts the small blind of 50 during the blind and antes round:<br>
</p>

<blockquote>
<p>
2011-07-17 06:59:38+0000 [-] <a class="missing wiki">PokerTable?</a>: Dealing hand Issgar 4/262007<br>
2011-07-17 06:59:38+0000 [-] [Server]<a class="missing wiki">11661?</a> Dealing Hold'em hand number 262007<br>
2011-07-17 06:59:38+0000 [-] [Server]<a class="missing wiki">11661?</a> player list: [9322, 10455, 8904, 11098, 9822, 11110, 11251]<br>
2011-07-17 06:59:38+0000 [-] [Server]<a class="missing wiki">11661?</a> changing state end =&gt; blindAnte<br>
2011-07-17 06:59:38+0000 [-] [Server]<a class="missing wiki">11661?</a> player 11110 pays blind 50/0<br>
2011-07-17 06:59:38+0000 [-] [Server]<a class="missing wiki">11661?</a> player 11251 pays blind 100/0<br>
</p>
</blockquote>

<p>
Then he rebuys 208 chips and sits in:<br>
</p>

<blockquote>
<p>
2011-07-17 06:59:46+0000 [HTTPChannel,43725,127.0.0.1] <a class="missing wiki">PokerTable?</a>: broadcast[8904, 10455, 11098, 9822, 11234, 11110, 9322, 11251] type = POKER_REBUY(85) serial = 11110 game_id = 11661 amount = 208 <br>
2011-07-17 06:59:46+0000 [HTTPChannel,43725,127.0.0.1] <a class="missing wiki">PokerTable?</a>: broadcast[8904, 10455, 11098, 9822, 11234, 11110, 9322, 11251] type = POKER_SIT(75) serial = 11110 game_id = 11661 <br>
</p>
</blockquote>

<p>
So does this mean he was sitting out when he posted the blind of 50? And how was<br>
he able to rebuy if he already posted the small blind?<br>
</p>

<p>
After all blinds and antes have been posted, player 11110 is no longer in the<br>
players list, and when the preflop round starts, he is not dealt cards. The log<br>
indicates he is waiting to play (reason=first_round).<br>
</p>

<blockquote>
<p>
2011-07-17 06:59:48+0000 [HTTPChannel,43868,127.0.0.1] [Server]<a class="missing wiki">11661?</a> player list: [9322, 10455, 8904, 9822, 11251]<br>
2011-07-17 06:59:48+0000 [HTTPChannel,43868,127.0.0.1] [Server]<a class="missing wiki">11661?</a> changing state blindAnte =&gt; pre-flop<br>
2011-07-17 06:59:48+0000 [HTTPChannel,43868,127.0.0.1] [Server]<a class="missing wiki">11661?</a> player 9322 cards: Th Ac<br>
2011-07-17 06:59:48+0000 [HTTPChannel,43868,127.0.0.1] [Server]<a class="missing wiki">11661?</a> player 10455 cards: Jh Qh<br>
2011-07-17 06:59:48+0000 [HTTPChannel,43868,127.0.0.1] [Server]<a class="missing wiki">11661?</a> player 8904 cards: Qc 5c<br>
2011-07-17 06:59:48+0000 [HTTPChannel,43868,127.0.0.1] [Server]<a class="missing wiki">11661?</a> player 9822 cards: 8d 7c<br>
2011-07-17 06:59:48+0000 [HTTPChannel,43868,127.0.0.1] [Server]<a class="missing wiki">11661?</a> player 11251 cards: 2c 6d<br>
2011-07-17 06:59:48+0000 [HTTPChannel,43868,127.0.0.1] [Server]<a class="missing wiki">11661?</a> new round pre-flop<br>
</p>
</blockquote>

<blockquote>
<p>
2011-07-17 06:59:48+0000 [HTTPChannel,43868,127.0.0.1] <a class="missing wiki">PokerTable?</a>: broadcast[8904, 10455, 11098, 9822, 11234, 11110, 9322, 11251] type = POKER_WAIT_FOR(103) serial = 11110 game_id = 11661 reason = first_round <br>
</p>
</blockquote>

<p>
Since player 11110 posted the small blind, shouldn't he be in the players list<br>
and have been dealt cards?<br>
</p>

<p>
During the preflop round player 11110 joins the table:<br>
</p>

<blockquote>
<p>
2011-07-17 07:00:00+0000 [HTTPChannel,43863,127.0.0.1] <a class="missing wiki">PokerAvatar?</a>: sendPacket(11110): type = POKER_TABLE(73)<br>
2011-07-17 07:00:00+0000 [HTTPChannel,43863,127.0.0.1]         id = 11661, name = Issgar 4, variant = holdem, betting_structure = .50-1-no-limit, seats = 10, average_pot = 4208, hands_per_hour = 40, percent_flop = 37, players = 8, observers = 3, waiting = 0, player_timeout = 30, muck_timeout = 5, currency_serial = 1, skin = default, tourney_serial = 0, reason = <a class="missing wiki">TableJoin?</a><br>
</p>
</blockquote>

<p>
I did not see any mention in the log about him leaving. Could he have been<br>
disconnected?<br>
</p>

<p>
When he joins, packets are sent to him as follows (see class<br>
<a class="missing wiki">PacketPokerTableJoin?</a> in pokernetwork/pokerpackets.py):<br>
</p>

<blockquote>
<p>
(0) In the case that the join is completely successful, or if the player<br>
</p>
<blockquote>
<p>
had already joined the table, the following packets are sent:<br>
</p>
</blockquote>

</blockquote>

<blockquote>
<blockquote>
<blockquote>
<p>
PACKET_POKER_TABLE<br>
PACKET_POKER_BATCH_MODE<br>
for each player in the game:<br>
</p>
<blockquote>
<p>
PACKET_POKER_PLAYER_ARRIVE<br>
</p>
</blockquote>

<p>
if the player is playing:<br>
</p>

<blockquote>
<blockquote>
<p>
PACKET_POKER_PLAYER_CHIPS<br>
</p>
</blockquote>

</blockquote>

<p>
if the player is sit:<br>
</p>

<blockquote>
<blockquote>
<p>
PACKET_POKER_SIT<br>
</p>
</blockquote>

</blockquote>

<p>
PACKET_POKER_SEATS<br>
if the game is running:<br>
</p>

<blockquote>
<blockquote>
<p>
the exact packet sequence that lead to the current state<br>
of the game. Varies according to the game.<br>
</p>
</blockquote>

</blockquote>

<p>
PACKET_POKER_STREAM_MODE<br>
</p>

</blockquote>
</blockquote>
</blockquote>

<blockquote>
<blockquote>
<p>
Note clearly that if the player had already previously joined the<br>
table, the packets above will be sent as if the player just joined.<br>
However, in that case, the packet will have no side effect.<br>
</p>
</blockquote>

</blockquote>

<p>
When rebroadcasting the start of the hand to player 11110, an exception is raised: <br>
</p>

<blockquote>
<p>
2011-07-17 07:00:00+0000 [HTTPChannel,43863,127.0.0.1] <a class="missing wiki">PokerAvatar?</a>: sendPacket(11110): type = POKER_START(66) serial = 0 game_id = 11661 hands_count = 1209, time = 398169, hand_serial = 262007, level = 0<br>
2011-07-17 07:00:00+0000 [HTTPChannel,43863,127.0.0.1] [11110]<a class="missing wiki">11661?</a> Dealing Hold'em hand number 262007<br>
2011-07-17 07:00:00+0000 [HTTPChannel,43863,127.0.0.1] [11110]<a class="missing wiki">11661?</a> changing state null =&gt; blindAnte<br>
2011-07-17 07:00:00+0000 [HTTPChannel,43863,127.0.0.1] [11110]<a class="missing wiki">11661?</a> initialisation turn 262007 ... finished<br>
2011-07-17 07:00:00+0000 [HTTPChannel,43863,127.0.0.1] <a class="missing wiki">PokerAvatar?</a>: sendPacket(11110): type = POKER_POSITION(54) game_id = 11661, position = 5, serial = 0<br>
2011-07-17 07:00:00+0000 [HTTPChannel,43863,127.0.0.1] <a class="missing wiki">PokerAvatar?</a>: Traceback (most recent call last):<br>
2011-07-17 07:00:00+0000 [HTTPChannel,43863,127.0.0.1]   File "/usr/lib/python2.6/dist-packages/pokernetwork/pokeravatar.py", line 328, in sendPacket<br>
2011-07-17 07:00:00+0000 [HTTPChannel,43863,127.0.0.1]     self.explain.explain(packet)<br>
2011-07-17 07:00:00+0000 [HTTPChannel,43863,127.0.0.1]   File "/usr/lib/python2.6/dist-packages/pokernetwork/pokerexplain.py", line 618, in explain<br>
2011-07-17 07:00:00+0000 [HTTPChannel,43863,127.0.0.1]     position_changed = serial_in_position != game.getSerialInPosition()<br>
2011-07-17 07:00:00+0000 [HTTPChannel,43863,127.0.0.1]   File "/usr/lib/python2.6/dist-packages/pokerengine/pokergame.py", line 3354, in getSerialInPosition<br>
2011-07-17 07:00:00+0000 [HTTPChannel,43863,127.0.0.1]     return self.player_list[self.position]<br>
2011-07-17 07:00:00+0000 [HTTPChannel,43863,127.0.0.1] <a class="missing wiki">IndexError?</a>: list index out of range<br>
</p>
</blockquote>

<p>
Notice that position = 5 is the position of player 11110 at the start of the<br>
hand. The possible cause of this exception may be described in the comment for<br>
sit(self, serial) in pokergame.py:<br>
</p>

<blockquote>
<p>
# Rationale of player.sit_out_next_turn == False<br>
# This condition happens when the player sitout + sit<br>
# while not having the position during the blind/ante round it.<br>
# In this particular case, instead of instructing her to wait<br>
# for the first round, she sits back. This is important because<br>
# she was included in the player list at the begining of the turn.<br>
# If she is marked wait_for = "first_round", she will be removed<br>
# from the player list at the end of the blind/ante round, which<br>
# is exactly the opposite of what we want.<br>
</p>
</blockquote>

<p>
Perhaps player 11110 was marked wait_for="first_round" and was removed from the<br>
player list at the end of the blind/ante round?<br>
</p>

<p>
There is another exception that is raised after the POKER_STREAM_MODE packet is<br>
sent:<br>
</p>

<blockquote>
<p>
2011-07-17 07:00:00+0000 [HTTPChannel,43863,127.0.0.1] <a class="missing wiki">PokerAvatar?</a>: sendPacket(11110): type = POKER_STREAM_MODE(104) serial = 0 game_id = 11661<br>
2011-07-17 07:00:01+0000 [HTTPChannel,43864,127.0.0.1] <a class="missing wiki">PokerService?</a>: *ERROR* avatar <a class="missing wiki">PokerAvatar?</a> serial = 11110, name = theFED is not in the list of known avatars<br>
</p>
</blockquote>

<p>
The cause for this is probably the same as the cause for the <a class="missing wiki">IndexError?</a>.<br>
</p>

<p>
Throughout the hand there are many 'unable to update position' errors:<br>
</p>

<blockquote>
<p>
2011-07-17 07:00:10+0000 [HTTPChannel,43846,127.0.0.1] [Server]<a class="missing wiki">11661?</a> ERROR: unable to update position<br>
</p>
</blockquote>

<p>
During the flop round, player 11110 joins the table again:<br>
</p>

<blockquote>
<p>
2011-07-17 07:00:36+0000 [HTTPChannel,43879,127.0.0.1] <a class="missing wiki">PokerAvatar?</a>: sendPacket(11177): type = POKER_TABLE(73)<br>
2011-07-17 07:00:36+0000 [HTTPChannel,43879,127.0.0.1]         id = 11683, name = Syfar 1, variant = holdem, betting_structure = 10-20-no-limit, seats = 10, average_pot = 35948, hands_per_hour = 120, percent_flop = 75, players = 1, observers = 0, waiting = 0, player_timeout = 180, muck_timeout = 5, currency_serial = 1, skin = default, tourney_serial = 0, reason = <a class="missing wiki">TableJoin?</a><br>
</p>
</blockquote>

<p>
The same <a class="missing wiki">IndexError?</a> and "avatar is not in the list of know avatars" errors occur<br>
when rebroadcasting the hand.<br>
</p>

<p>
Before the hand ends, player 11110 leaves the table:<br>
</p>

<blockquote>
<p>
2011-07-17 07:00:57+0000 [-] [Server]<a class="missing wiki">11661?</a> removing player 11110 from game<br>
2011-07-17 07:00:57+0000 [-] <a class="missing wiki">PokerAvatar?</a>: sendPacket(11110): type = POKER_PLAYER_LEAVE(81) serial = 11110 game_id = 11661 seat = 7<br>
2011-07-17 07:00:57+0000 [-] [11110]<a class="missing wiki">11661?</a> removing player 11110 from game<br>
2011-07-17 07:00:57+0000 [-] <a class="missing wiki">PokerTable?</a>: broadcast[8904, 10455, 11098, 9822, 11234, 9322, 11251] type = POKER_PLAYER_LEAVE(81) serial = 11110 game_id = 11661 seat = 7 <br>
2011-07-17 07:00:57+0000 [-] [8904]<a class="missing wiki">11661?</a> removing player 11110 from game<br>
2011-07-17 07:00:57+0000 [-] [10455]<a class="missing wiki">11661?</a> removing player 11110 from game<br>
2011-07-17 07:00:57+0000 [-] [11098]<a class="missing wiki">11661?</a> removing player 11110 from game<br>
2011-07-17 07:00:57+0000 [-] [9822]<a class="missing wiki">11661?</a> removing player 11110 from game<br>
2011-07-17 07:00:57+0000 [-] [11234]<a class="missing wiki">11661?</a> removing player 11110 from game<br>
2011-07-17 07:00:57+0000 [-] [9322]<a class="missing wiki">11661?</a> removing player 11110 from game<br>
2011-07-17 07:00:57+0000 [-] [11251]<a class="missing wiki">11661?</a> removing player 11110 from game<br>
2011-07-17 07:00:57+0000 [-] <a class="missing wiki">11661?</a> removing player 11110 from game<br>
2011-07-17 07:00:57+0000 [-] [24]<a class="missing wiki">11661?</a> removing player 11110 from game<br>
2011-07-17 07:00:57+0000 [-] <a class="missing wiki">PokerService?</a>: leavePlayer UPDATE user2money,user2table,pokertables SET  user2money.amount = user2money.amount + user2table.money + user2table.bet  WHERE user2money.user_serial = user2table.user_serial AND        user2money.currency_serial = pokertables.currency_serial AND        pokertables.serial = 11661 AND        user2table.table_serial = 11661 AND        user2table.user_serial = 11110<br>
2011-07-17 07:00:57+0000 [-] <a class="missing wiki">PokerService?</a>: leavePlayer DELETE from user2table  WHERE user_serial = 11110 AND        table_serial = 11661<br>
</p>
</blockquote>

<p>
Finally after the hand is completed, there is an error when distributing the<br>
rake:<br>
</p>

<blockquote>
<p>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1] <a class="missing wiki">PokerResource?</a>: *ERROR* (x-forwarded-for:71.202.181.6) Traceback (most recent call last):<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]   File "/usr/lib/python2.6/dist-packages/twisted/internet/defer.py", line 213, in addCallbacks<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]     self._runCallbacks()<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]   File "/usr/lib/python2.6/dist-packages/twisted/internet/defer.py", line 371, in _runCallbacks<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]     self.result = callback(self.result, *args, **kw)<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]   File "/usr/lib/python2.6/dist-packages/pokernetwork/pokersite.py", line 237, in &lt;lambda&gt;<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]     deferred.addCallback(lambda result: self.deferRender(request, jsonp, packet, data))<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]   File "/usr/lib/python2.6/dist-packages/pokernetwork/pokersite.py", line 248, in deferRender<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]     d = defer.maybeDeferred(session.avatar.handleDistributedPacket, request, packet, data)<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1] --- &lt;exception caught here&gt; ---<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]   File "/usr/lib/python2.6/dist-packages/twisted/internet/defer.py", line 117, in maybeDeferred<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]     result = f(*args, **kw)<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]   File "/usr/lib/python2.6/dist-packages/pokernetwork/pokeravatar.py", line 424, in handleDistributedPacket<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]     return self.handlePacketDefer(packet)<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]   File "/usr/lib/python2.6/dist-packages/pokernetwork/pokeravatar.py", line 483, in handlePacketDefer<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]     self.handlePacketLogic(packet)<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]   File "/usr/lib/python2.6/dist-packages/pokernetwork/pokeravatar.py", line 866, in handlePacketLogic<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]     game.fold(packet.serial)<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]   File "/usr/lib/python2.6/dist-packages/pokerengine/pokergame.py", line 2042, in fold<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]     self.<span class="underline">talked(serial)<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]   File "/usr/lib/python2.6/dist-packages/pokerengine/pokergame.py", line 2245, in </span>talked<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]     self.muckState(WON_FOLD)<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]   File "/usr/lib/python2.6/dist-packages/pokerengine/pokergame.py", line 1723, in muckState<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]     self.setRakedAmount(self.rake.getRake(self))<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]   File "/usr/lib/python2.6/dist-packages/pokerengine/pokergame.py", line 1751, in setRakedAmount<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]     self.historyAdd("rake", rake, self.getRakeContributions())<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]   File "/usr/lib/python2.6/dist-packages/pokerengine/pokergame.py", line 1770, in getRakeContributions<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]     return self.distributeRake(rake, total, serial2share)<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]   File "/usr/lib/python2.6/dist-packages/pokerengine/pokergame.py", line 1789, in distributeRake<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1]     contribution += self.getPlayer(serial).dead<br>
2011-07-17 07:01:13+0000 [HTTPChannel,43862,127.0.0.1] exceptions.<a class="missing wiki">AttributeError?</a>: '<a class="missing wiki">NoneType?</a>' object has no attribute 'dead'<br>
</p>
</blockquote>

<p>
<a class="missing wiki">PokerGame?</a>.getPlayer(serial) returns None -- perhaps because player 11110 left<br>
the table, or was not part of the players list?<br>
</p>

<p>
At this point the table is in a "crashed" state in the sense that play is<br>
stopped. A new hand is not being dealt, and when observers join the table they<br>
see hand <a class="missing ticket">#262007</a> being replayed.<br>
</p>

**Comment by hippich** [comment]
Raw log - http://pastebin.com/raw.php?i=853Bg8DW

**Comment by hippich** [comment]
Today another table ended in crashed state. 

Here is actual error:

```
2011-07-29 04:19:29+0000 [HTTPChannel,1596,127.0.0.1] [Server][PokerGame 14290] ERROR: unable to update position
```

And a little bit later this happens:

`2011-07-29 04:19:40+0000 [HTTPChannel,1516,127.0.0.1] [11215][PokerGame 14290] Dealing Hold'em hand number 297509
2011-07-29 04:19:40+0000 [HTTPChannel,1516,127.0.0.1] PokerAvatar: Traceback (most recent call last):
2011-07-29 04:19:40+0000 [HTTPChannel,1516,127.0.0.1]   File "/usr/lib/python2.6/dist-packages/pokernetwork/pokeravatar.py", line 328, in sendPacket
2011-07-29 04:19:40+0000 [HTTPChannel,1516,127.0.0.1]     self.explain.explain(packet)
2011-07-29 04:19:40+0000 [HTTPChannel,1516,127.0.0.1]   File "/usr/lib/python2.6/dist-packages/pokernetwork/pokerexplain.py", line 323, in explain
2011-07-29 04:19:40+0000 [HTTPChannel,1516,127.0.0.1]     game.beginTurn(packet.hand_serial)
2011-07-29 04:19:40+0000 [HTTPChannel,1516,127.0.0.1]   File "/usr/lib/python2.6/dist-packages/pokerengine/pokergame.py", line 982, in beginTurn
2011-07-29 04:19:40+0000 [HTTPChannel,1516,127.0.0.1]     if not self.buildPlayerList(True):
2011-07-29 04:19:40+0000 [HTTPChannel,1516,127.0.0.1]   File "/usr/lib/python2.6/dist-packages/pokernetwork/pokergameclient.py", line 58, in buildPlayerList
2011-07-29 04:19:40+0000 [HTTPChannel,1516,127.0.0.1]     assert self.player_list == filter(lambda x: self.serial2player[x].isSit(), self.player_list)
2011-07-29 04:19:40+0000 [HTTPChannel,1516,127.0.0.1] AssertionError`

Here is full log - http://ubuntuone.com/p/170Y/

**Comment by anisoptera** [comment]
Thanks to @gg for help on the repro.
